module.exports = {
  registerationDesk:
    '#referenceapplication-registrationapp-registerPatient-homepageLink-referenceapplication-registrationapp-registerPatient-homepageLink-extension',
  firstName: 'input[name : givenName]',
  middleName: 'input[name : middleName]',
  familyName: 'input[name : familyName]',
  button: '#next-button',
  gender: '#gender-field',
  nextGenderButton: '#next-button > .fas',
  birthDate: '#birthdateDay-field',
  birthMonth: '#birthdateMonth-field',
  bithYear: '#birthdateYear-field',
  address1: '#address1',
  address2: '#address2',
  city: '#cityVillage',
  state: '#stateProvince',
  country: '#country',
  postalCode: '#postalCode',
  phoneNumber: 'input[name : phoneNumber]',
  relationShip: '#relationship_type',
  person: '.person-typeahead',
  submitButton: '#submit',
  appointmentTypeInput: '#appointment-type',
  logOutButton: '.icon-signout',
  userName: '#username',
  password: '#password',
  loginButton: '#loginButton',
  invalidLocation: '#sessionLocationError',
}
