export function getRefundPayload(invoiceNumber, invoiceValue, orderId) {
  return {
    invoiceNumber,
    invoiceValue,
    issuanceDate: new Date(),
    type: 'Input',
    items: [
      {
        uniqueId: '3C851E5766644AA18D67DF3A3ED14F73',
        id: '880300',
        productId: '880030',
        ean: null,
        lockId: `00-${orderId}`,
        itemAttachment: {
          content: {},
          name: null,
        },
        attachments: [],
        quantity: 2,
        seller: '1',
        name: 'Fresh Coconuts',
        refId: '880300a',
        price: 54000,
        listPrice: 54000,
        manualPrice: null,
        priceTags: [],
        imageUrl:
          'https://productusqa.vteximg.com.br/arquivos/ids/155670-55-55/fresh-coconuts.jpg?v=637745847017730000',
        detailUrl: '/fresh-coconuts/p',
        components: [],
        bundleItems: [],
        params: [],
        offerings: [],
        sellerSku: '880300',
        priceValidUntil: null,
        commission: 0,
        tax: 0,
        preSaleDate: null,
        additionalInfo: {
          brandName: 'Brand',
          brandId: '9280',
          categoriesIds: '/9282/',
          categories: [
            {
              id: 9282,
              name: 'Food and beverage',
            },
          ],
          productClusterId: '139,141,145,146,147,148',
          commercialConditionId: '1',
          dimension: {
            cubicweight: 0.2083,
            height: 10,
            length: 10,
            weight: 10,
            width: 10,
          },
          offeringInfo: null,
          offeringType: null,
          offeringTypeId: null,
        },
        measurementUnit: 'un',
        unitMultiplier: 1,
        sellingPrice: 54000,
        isGift: false,
        shippingPrice: null,
        rewardValue: 0,
        freightCommission: 0,
        priceDefinition: {
          sellingPrices: [
            {
              value: 54000,
              quantity: 2,
            },
          ],
          calculatedSellingPrice: 54000,
          total: 108000,
        },
        taxCode: null,
        parentItemIndex: null,
        parentAssemblyBinding: null,
        callCenterOperator: null,
        serialNumbers: null,
        assemblies: [],
        costPrice: 54000,
        index: 0,
        taxHubTotal: 0,
        warehouseId: '1_1',
        hasManualPrice: false,
        originalSellingPrice: 54000,
        selectableQuantity: [1, 2],
        selectedQuantity: 2,
        isSelected: true,
      },
    ],
  }
}
